### ISSUE TITLE
Enhance readme for local build

### ISSUE THREAD

**Issue by chheis** [COVESA/Open1722#42]
Could we add?
For Ubunut Users install:
CMocka with:
sudo apt-get install libcmocka-dev

**Comment by nayakned** [comment]
@chheis The cmake build has been adapted to handle cmocka as a dependency and the Readme has been updated to reflect your feedback. Let me know if you think more changes are required before we close this issue. Thanks.

**Comment by SebastianSchildt** [comment]
Closing this now. Reopen if something is missing
